spring:
  application:
    name: consumer-hello
  main:
    allow-bean-definition-overriding: true
dubbo:
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: life.gmy.spring.cloud.alibaba.example.provider.service
  cloud:
    subscribed-services: provider-hello